[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
  NODE_VERSION = "11.15.0"
  # RUBY_VERSION = "2.6.2"
  REACT_APP_CONTEXT = "production"
	# GRAPH_API_URL="https://api-shasta.oikos.exchange"

[context.branch-deploy.environment]
  REACT_APP_CONTEXT = "staging"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"

